* Introduction
Qint (Quasar internationalization) is a library that facilitate the i18n of
Quasar apps. Qint extends [[https://github.com/pyxo-dev/vint][Vint]].

* Installation
#+begin_src sh
yarn add vue-i18n@next
yarn add @pyxo/qint
# or
npm install vue-i18n@next
npm install @pyxo/qint
#+end_src

For an easier way to get started, see the app extension [[https://github.com/pyxo-dev/quasar-app-extension-int][Int]].

* Features
- SSR support.
- Supports different URL modes: prefix (example.com/en), subdomain
  (en.example.com), host (example.co.uk), search-param (example.com?l=en), none
  (example.com)
- Supports the use of a language tag cookie.
- Can make use of the user's client language preferences (e.g. browser
  settings).
- Support for =hreflang= link tags.
- Lazy loading of Quasar language packs and =vue-i18n= locale messages.
- Language tags, Qint uses the term "language tag" to denote a language or a
  locale, and recommends the use of [[https://www.w3.org/International/articles/language-tags][BCP 47]] language tags.

* Documentation
API docs: [[https://qint.pyxo.net/api][qint.pyxo.net/api]]

* Source code
Repository: [[https://github.com/pyxo-dev/qint][github.com/pyxo-dev/qint]]

Contributions are welcome!

* See also
- [[https://github.com/pyxo-dev/wint][Wint]] Web apps int.
- [[https://github.com/pyxo-dev/vint][Vint]] Vue int.
- [[https://github.com/pyxo-dev/quasar-app-extension-int][Int]] Quasar Int app extension.
